### ISSUE TITLE
Spanish translation improvements

### ISSUE THREAD

**Issue by karlcabaniya** [bombmanual/bombmanual.github.io#25]
Some translations of the Spanish manual are odd because it is hard to find a matching term in Spanish. Here are two suggestions to help you improving the quality of the translation while remaining true to the original manual.

On the Subject of... = En la materia de... (instead of "En caso de...").
Needy Modules = Módulos necesitados (instead of "Módulos necesarios").

**Comment by yeuk0** [comment]
Hi @karlcabaniya,

I posted yesterday some improvements I was thinking to merge here https://steamcommunity.com/app/341800/discussions/0/481115363855491836/?ctp=8#c1694917906675769080
I replaced "On the Subject of" for "Acerca de..." and "Needy Modules" for "Módulos necesitados de su atención" in section's title and "Módulos necesitados" for other appearances, among other things. In Steam Community you can see a changelog (in Spanish) that I'm going to put here to if the community gives me his aproval.

**Comment by brugnara** [comment]
Hi @karlcabaniya and @yeuk0

Does #26 fix this issue?

Thank you.

**Comment by yeuk0** [comment]
Yep, it should. Its suggestions were not taken as it wrote them, but those translations were modified by others which fit better than previous ones:

On the Subject of... = "Acerca de..." (instead of "En caso de..." or "En la materia de...")
Needy Modules = "Módulos demandantes" (instead of "Módulos necesarios" or "Módulos necesitados")

**Comment by brugnara** [comment]
Ok, then I'm closing this. 

Thank you.
